"""empty message

Revision ID: 52312a31b9ed
Revises: 
Create Date: 2024-08-13 21:54:47.044209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52312a31b9ed'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('name', sa.String(), nullable=False),
            sa.Column('email', sa.String(), nullable=False),
            sa.Column('password', sa.String(), nullable=False),
            sa.Column('registred_at', sa.TIMESTAMP(), nullable=True),
            sa.PrimaryKeyConstraint('id')
    )
    op.create_table('programs',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('file_name', sa.String(), nullable=False),
            sa.Column('text', sa.Text(), nullable=False),
            sa.Column('user_id', sa.Integer(), nullable=True),
            sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
            sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('programs')
    op.drop_table('users')
    # ### end Alembic commands ###
